
version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: biblioteca
      POSTGRES_PASSWORD: biblioteca
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "biblioteca"
      PGADMIN_DEFAULT_PASSWORD: "biblioteca"
    ports:
      - "8085:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge